version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./pscapp
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.hibernate.ddl-auto" : "create-drop" ,  
        "mailstrap.username" : "api",
        "mailstrap.password" : "dd05f45be13af56332d53dec9b2ab3d2",
        "mailstrap.host" : "live.smtp.mailtrap.io",
        "mailstrap.props_mail_smtp_auth" : "true",
        "mailstrap.props_mail_smtp_starttls_enable" : "true",
        "mailstrap.props_mail_smtp_host" : "host",
        "mailstrap.props_mail_smtp_port" : "587",
        "spring.mail.protocol" : "smtp",
        "spring.mail.host" : "smtp.mailtrap.io",
        "spring.mail.properties.mail.smtp.auth" : "true",
        "spring.mail.properties.mail.smtp.starttls.enable" : "true"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
