
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:4499/jardineria?createDatabaseIfNotExist=true
    username: root
    password: eneas2805
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        format-sql: true
server:
   port: 8093