spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3399/jardineria
    username: root
    password: eneas2805
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format-sql: false
server:
   port: 8093